#cloud-config

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    home: /home/ubuntu
    shell: /bin/bash

ssh_pwauth: false
disable_root: false
chpasswd:
  list: |
    ubuntu:ubuntu
  expire: false

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

package_update: true
package_upgrade: true
packages:
  - docker-ce
  - docker-ce-cli
  - docker-compose
  - iptables-persistent
  
write_files:
   - path: /home/ubuntu/docker-compose.yaml
     content: |
       version: '3.7'
       services:
         nginx:
           container_name: binginx
           image: "detree05/binginx:latest"
           restart: always
           ports:
             - "80:80"
             - "443:443"
             - "8443:8443"
           deploy:
             resources:
               limits:
                 memory: 512M
         bingo-1:
           container_name: uno-bingo
           image: "detree05/bingo:latest"
           restart: always
           ports:
             - "8080:7962"
           deploy:
             resources:
               limits:
                 memory: 1G
           healthcheck:
             test: ["CMD-SHELL", "curl localhost:7962/ping | grep pong || kill 1" ]
             interval: 1s
             timeout: 3s
             retries: 1
             start_period: 5s
         bingo-2:
           container_name: des-bingo
           image: "detree05/bingo:latest"
           restart: always
           ports:
             - "8081:7962"
           deploy:
             resources:
               limits:
                 memory: 1G
           healthcheck:
             test: ["CMD-SHELL", "curl localhost:7962/ping | grep pong || kill 1" ]
             interval: 1s
             timeout: 3s
             retries: 1
             start_period: 5s

runcmd:
  - [ sh, -c, 'sudo iptables -t nat -A PREROUTING -p tcp -d 8.8.8.8 --dport 80 -j DNAT --to-destination 8.8.8.8:53' ]
  - [ sh, -c, 'sudo iptables-save > /etc/iptables/rules.v4' ]
  - [ sh, -c, 'cd /home/ubuntu && sudo docker-compose up' ]