#cloud-config

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    home: /home/ubuntu
    shell: /bin/bash

disable_root: false
chpasswd:
  list: |
    ubuntu:ubuntu
  expire: false

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

package_update: true
package_upgrade: true
packages:
  - docker-ce
  - docker-ce-cli
  - docker-compose
  - iptables-persistent
  
write_files:
   - path: /home/ubuntu/docker-compose.yaml
     content: |
       version: '3.7'
       services:
         postgresql:
           container_name: bingo-db
           image: "detree05/postgres:latest"
           restart: always
           ports:
              - "5432:5432"
           volumes:
             - data:/var/lib/postgresql/data
           healthcheck:
             test: ["CMD-SHELL", "pg_isready -U postgres || kill 1"]
             interval: 5s
             timeout: 5s
             retries: 3
             start_period: 60s
           deploy:
             resources:
               limits:
                 memory: 2G
           shm_size: 1G
       volumes:
         data:

runcmd:
  - [ sh, -c, 'sudo iptables -A DOCKER -p tcp -s 10.5.0.0/24 --dport 5432 -j ACCEPT && sudo iptables -A DOCKER -p tcp --dport 5432 -j DROP' ]
  - [ sh, -c, 'sudo iptables-save > /etc/iptables/rules.v4' ]
  - [ sh, -c, 'cd /home/ubuntu && sudo docker-compose up' ]