version: '3.7'
services:
  postgresql:
    container_name: bingo-db
    image: "detree05/postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || kill 1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 2G
    shm_size: 1G
volumes:
  data:
