version: '3.7'
services:
  postgresql:
    container_name: bingo-db
    image: "detree05/postgres:latest"
    restart: always
    network_mode: "host"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
